#!/bin/bash

set -eux
cd $(dirname $0)
git worktree add site origin/gh-pages
mkdocs build --clean && cp CNAME site
(cd site && git add . && git commit -m 'update docs' && git push origin HEAD:gh-pages)
rm -Rf site
git worktree prune

