name: Publish package to GitHub Packages
on:
  push:
    branches:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: wget -O $RUNNER_TEMP/java_package.tar.gz "https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '11'
          architecture: x64
      - name: Set package version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Echo package version
        run: echo $RELEASE_VERSION
      - name: Publish package
        run: mvn --batch-mode deploy -Dmaven.test.skip=true -Dgpg.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
